

spring:
  redis:
    database: 0
    host: 192.168.126.134
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000

server:
  port: 8083